---

# Launch EC2 instance

- name: Launch the new EC2 Instance
  ec2:
    instance_type: "{{ ec2.instance_type }}"
    region: "{{ ec2.region }}"
    count: "{{ ec2.count }}"
    group: "{{ ec2.security_group }}"
    vpc_subnet_id: "{{ ec2.vpc_subnet_id }}"
    image: "{{ ec2.image }}"
    keypair: "{{ ec2.keypair }}"
    assign_public_ip: "{{ ec2.assign_public_ip }}"
    wait: "{{ ec2.wait }}"
  register: ec2


# Adding host to 'webservers group'

- name: Add the newly created host
  add_host:
    name: "{{ item.public_ip }}"
    groups: webservers
  with_items: "{{ ec2.instances }}"


# Connecting to remote server via ssh

- name: 'Wait for SSH to come up'
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  with_items:
    - "{{ ec2.instances }}"


# Adding tags

- name: Add tag to Instance
  local_action: ec2_tag resource={{ item.id }}
                region={{ item.region }}
                state=present
  with_items:
    - "{{ ec2.instances }}"
  args:
    tags:
      Type: webserver
